#include <iostream>
#include <allegro5/allegro.h>
#include <stdio.h>
#include "entorno.h"
using namespace std;
int main(int argc, char** argv){
entornoIniciar (10);
entornoPonerEntrada(0,0,0.5);
entornoPonerSalida(9,9);
entornoTerminar();
entornoIniciar(7);
entornoPonerEntrada(6,5,0.5);
entornoPonerSalida(2,0);
entornoMostrarMensaje("OBSTACULOS");
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(6,0);
entornoPonerObstaculo(4,6);
entornoPonerObstaculo(4,5);
entornoPonerObstaculo(4,4);
entornoPonerObstaculo(4,3);
entornoPonerObstaculo(4,2);
entornoPonerObstaculo(3,2);
entornoPonerObstaculo(2,2);
entornoPonerObstaculo(1,2);
entornoPonerObstaculo(0,2);
entornoPonerObstaculo(0,2);
entornoPonerObstaculo(0,3);
entornoPonerObstaculo(0,4);
entornoPonerObstaculo(0,4);
entornoPonerEntrada(6,5,0.4);
entornoPonerSalida(2,0);
entornoPonerEntrada(6,5,0.4);
entornoPonerSalida(2,0);
entornoMostrarMensaje("Soy Ejemplo 1");
entornoPonerFigura(6,4,0.4);
entornoPonerFigura(6,3,0.4);
entornoPonerFigura(6,2,0.4);
entornoPonerFigura(6,1,0.4);
entornoPonerFigura(5,1,0.4);
entornoPonerFigura(4,1,0.4);
entornoPonerFigura(3,1,0.4);
entornoPonerChoque(3,2);
entornoMostrarMensaje ("  ¡ Mala suerte !    ");
entornoPonerEntrada(6,5,0.4);
entornoPonerSalida(2,0);
entornoMostrarMensaje("Soy Ejemplo 2");
entornoPonerFigura(5,5,0.4);
entornoPonerFigura(5,4,0.4);
entornoPonerFigura(5,3,0.4);
entornoPonerFigura(6,3,0.4);
entornoPonerFigura(6,2,0.4);
entornoPonerFigura(6,1,0.4);
entornoPonerChoque(6,0);
entornoMostrarMensaje ("  ¡ Mala suerte !    ");
entornoPonerEntrada(6,5,0.4);
entornoPonerSalida(2,0);
entornoMostrarMensaje("Soy Ejemplo 3");
entornoPonerFigura(6,4,0.4);
entornoPonerFigura(6,3,0.4);
entornoPonerFigura(6,2,0.4);
entornoPonerFigura(6,1,0.4);
entornoPonerFigura(5,1,0.4);
entornoPonerFigura(4,1,0.4);
entornoPonerFigura(3,1,0.4);
entornoPonerFigura(2,1,0.4);
entornoPonerFigura(3,1,0.4);
entornoPonerFigura(3,0,0.4);
entornoPonerFigura(2,0,0.4);
entornoPonerFiguraSalida(2,0);
entornoMostrarMensaje ("  ¡ Lo conseguiste !    ");
entornoMostrarMensaje ("  ¡ Lo conseguiste !    ");
entornoMostrarMensajeFin ("  ¡ Fin !    ");
entornoTerminar();
entornoPausa(1);
return 0;
}
